name: deploy blog react

on:
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - '**'

  
jobs: 
    deploy:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2 # 第三方 action

        - name: set id_sra # 设置 id_sra 
          run: |
            mkdir -p ~/.ssh/
            echo "${{secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ls -l /home/runner/.ssh/id_rsa
            chmod 600 /home/runner/.ssh/id_rsa
            ls -ld /home/runner/.ssh
            sudo chown runner: /home/runner/.ssh
            sudo chown runner: /home/runner/.ssh/id_rsa
            ssh-keyscan 120.26.123.78 >> ~/.ssh/known_hosts

        - name: deploy # 自动发布
          run: |
            ssh root@120.26.123.78 "
              # 服务器已经执行过 git clone 到 /www/wwwroot/blog/blog-react
              cd ../www/wwwroot/blog/blog-react;
              git checkout . ;
              git checkout main;
              git pull origin main;

              # 重启服务
              npm install;
              npm run build;
            "

        - name: delete id_rsa # 及时删除 id_rsa
          run: rm -rf ~/.ssh/id_rsa